# Generated by Django 6.0.6 on 2026-06-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_auto_assign_to'),
        ('tickets', '0005_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to make this category available for all departments.', related_name='categories', to='departments.department'),
        ),
    ]
